version: 2
jobs:
  build:
    docker:
      - image: whill/clang-gtest:0.0.1

    working_directory: ~/circleci-clang

    steps:
      - checkout

      # run tests!
      - run:
          name: run tests
          command: |
            chmod a+x build.sh
            ./build.sh

      - store_test_results:
          path: test-results